{
    'name': 'CIDS DESIGN Theme',
    'description': 'CIDS HOME PAGE',
    'category': 'Theme',
    'sequence': 10,
    'version': '1.0',
    'depends': ['website','web'],
    'data': [
        'views/assets.xml',
        'views/header.xml',
        'views/home.xml',
        'views/footer.xml',
        'views/commercial.xml',
        # 'views/landing_page.xml',
        'views/ffe.xml',
        'views/hospitality.xml',
        'views/how_we_design.xml',
        'views/our_principles.xml',
        'views/about.xml',
        'views/contactus.xml',
        'views/site_map.xml',
        'views/thanku_contact_us.xml',
        'views/team.xml',
        # 'views/snippets/home.xml',
        # 'views/snippets/landing.xml',
        # 'views/snippets/hospitality.xml',
        # 'views/snippets/commercial.xml'
        # 'views/snippets/home/banner.xml',
        # 'views/snippets/home/about_us.xml',
        # 'views/snippets/home/about_us2.xml',
        # 'views/snippets/home/accreditation.xml',
        # 'views/snippets/home/case_studies.xml',
        # 'views/snippets/home/designer_work.xml',
        # 'views/snippets/home/services.xml',
        # 'views/snippets/home/testimonal.xml',
        # 'views/snippets/home/follow_us.xml',
        # 'views/snippets/landing/about_banner.xml',
        # 'views/snippets/landing/about_cids.xml',
        # 'views/snippets/landing/cids_process.xml',
        # 'views/snippets/landing/hotel_services.xml',
        # 'views/snippets/landing/hotel_projects.xml',
        # 'views/snippets/landing/happy_customers.xml',
        # 'views/snippets/landing/why_us.xml'
    ],
    'images': [
    ],
    'assets':{
        'web.assets_frontend': [
            # 'cids_theme_odoo_15/static/src/scss/style.scss',
            # 'cids_theme_odoo_15/static/src/scss/footer.scss',
            'cids_theme_odoo_15/static/src/scss/header.scss',
            'cids_theme_odoo_15/static/src/scss/animate.css',
            'cids_theme_odoo_15/static/src/scss/home_page.scss',
            'cids_theme_odoo_15/static/src/scss/how_we_design.scss',
            'cids_theme_odoo_15/static/src/scss/team.scss',
            'cids_theme_odoo_15/static/src/scss/our_principles.scss',
            'cids_theme_odoo_15/static/src/scss/font-awesome.min.css',
            # 'cids_theme_odoo_15/static/src/scss/landing_style.scss',
            # 'cids_theme_odoo_15/static/src/scss/hospitality_style.scss',
            # 'cids_theme_odoo_15/static/src/scss/commercial_style.scss',
            'cids_theme_odoo_15/static/src/scss/owl.scss',
            'cids_theme_odoo_15/static/src/scss/owltheme.scss',
            # 'cids_theme_odoo_15/static/src/js/cidsjquery.js',
            # 'cids_theme_odoo_15/static/src/js/cids.js',

            'cids_theme_odoo_15/static/src/js/owl.js',
            'cids_theme_odoo_15/static/src/js/gallery.js',
            'cids_theme_odoo_15/static/src/js/home_page.js',

        ],
    },
    'snippet_lists': {
    },
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
